### PR TITLE
Add 16-bit format support

### PR DESCRIPTION
**Pull request by spencer-lunarg**
`layout(location = 0) in float16_t a;` was showing `SPV_REFLECT_FORMAT_UNDEFINED` but now shows `SPV_REFLECT_FORMAT_R16_SFLOAT` as expected

### CODE REVIEW

**Review by chaoticbob — COMMENTED** [review]
Is there a source file for vert_in_out_16.spv?

**Comment by spencer-lunarg** [comment]
there was a glsl file, not going to lie I lost it, can get it back though quick

**Comment by chaoticbob** [comment]
Might be useful to have around in case it's needed in the future for som reason.

**Comment by chaoticbob** [comment]
Awesome, thanks!

**Review by chaoticbob — APPROVED** [review]

**Pull request merged**
